version: '3.8'

services:
  portainer:
    container_name: portainer2
    image: portainer/portainer-ce:latest
    restart: always
    ports: 
      - '9000:9000'
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: